version: 2
jobs:
  test-gen-example:
    docker:
      - image: circleci/golang:1.12
    environment:
      - GO111MODULE: "on"
    working_directory: /go/src/github.com/sganon/{{REPO_NAME}}
    steps:
      - checkout
      - run: go install .
      - run: cd example && go generate
      - run: go test -v ./example 
      - run: cd example && go generate # the generated test should generate a file which can then be regenerated if necessary and still be valid
      - run: go test -v ./example

workflows:
  version: 2
  pipeline:
    jobs:
      - test-gen-example
